version: '3'
services:
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
#    environment:
#      - discovery.type=single-node
#    ports:
#      - "9201:9200"
#    networks:
#      - myapp_myapp_network

  springboot-app:
    build:
      context: .
    ports:
      - "8082:8080"
#    depends_on:
#      - elasticsearch
#    networks:
#      - myapp_myapp_network
#
#networks:
#  myapp_myapp_network:
#    external: true
